### PR TITLE
Bugfix/event listener callback issue

### LINKED ISSUE #91: Inconsistent behaviour when registering event listeners
### Expected Behaviour
Whether registering an event listener before or after **adobe-client-data-layer.min.js** has loaded, the callback function should fire just once

### Actual Behaviour
When registering an event listener before **adobe-client-data-layer.min.js** has loaded, the callback function fires twice (fires just once when registering it after the library has loaded)

#### Steps to Reproduce
Navigate to about:blank in a browser
Execute the following in the console (registers the callback before the library loads)
```
window.adobeDataLayer = []
instance = 1

var myHandler = function(event) {
    console.log('Instance: ' + instance)
    console.log(event)
    instance+=1
}

window.adobeDataLayer.push(function(dl) {
    dl.addEventListener(
        "adobeDataLayer:event", 
        myHandler
    )
})

window.adobeDataLayer.push({'event':'newEvent','context':'test'})
scriptElement = document.createElement('script');
scriptElement.src="https://unpkg.com/@adobe/adobe-client-data-layer@1.0.0/dist/adobe-client-data-layer.min.js";
document.body.append(scriptElement)
```

(Optional) Execute the following in the console (registers the callback after the library loads)
```
window.adobeDataLayer = []
window.adobeDataLayer.push({'event':'newEvent','context':'test'})
scriptElement = document.createElement('script');
scriptElement.src="https://unpkg.com/@adobe/adobe-client-data-layer@1.0.0/dist/adobe-client-data-layer.min.js";
document.body.append(scriptElement)

instance = 1

var myHandler = function(event) {
    console.log('Instance: ' + instance)
    console.log(event)
    instance+=1
}

window.adobeDataLayer.push(function(dl) {
    dl.addEventListener(
        "adobeDataLayer:event", 
        myHandler
    )
})
```

#### Platform and Version
Chrome 83.0.4103.116

### LINKED ISSUE #100: [Regression] getState method returns no data in event callback
When pushing a callback on the `adobeDataLayer` stack that is to be executed as soon as the `adobeDataLayer` object initializes, then it seems that `adobeDataLayer.getState()` doesn't work properly.

This worked in 1.0.0, even though incorrectly as the callbacks got called twice: once with the data not available via `adobeDataLayer.getState()` and once with the data available. In 1.1.0, the callback is called once only, but only with no more data available via `adobeDataLayer.getState()`.

### Steps to reproduce

Navigate to `about:blank` URL in a browser, and execute the following JS in the brower console:
```javascript
window.adobeDataLayer = [];
instance = 0;

adobeDataLayer.push(function(dl) {
    dl.addEventListener(
        "new event", 
        function(event) {
            console.log("callback " + ++instance, dl.getState());
        }
    )
});

adobeDataLayer.push({
    event: "new event",
    context: "test"
});

acdl = document.createElement("script");
acdl.src = "https://unpkg.com/@adobe/adobe-client-data-layer@1.1.0/dist/adobe-client-data-layer.min.js";
document.body.append(acdl);
```

The above code incorrectly logs:
```
callback 1 {}
```

It would have been expected to log:
```
callback 1 { context: "test" }
```

When changing the `adobe-client-data-layer` script version to `1.0.0`, then the callback gets wrongly executed twice, but the second time with the correct data available:
```
callback 1 {}
callback 2 { context: "test" }
```

This change was introduced via #92, and it seems like it didn't correctly fix the entire problem.

### PR DESCRIPTION
**Pull request by bartoszglow**
Closes #100 
Closes #91

This PR:
- makes the data layer always behave the same: it does not matter whether the custom code is executed before or after the data layer script has loaded
- makes the callback function fire just once, whether registering an event listener before or after adobe-client-data-layer.min.js has loaded
- adds tests to verify the behavior
- adds tests to verify nested anonymous functions behaviour

Examples:

1. Event listener with scope set to past, late ACDL initialization:
```
  adobeDataLayer.push(function(adobeDataLayer) {
    adobeDataLayer.addEventListener('change', function(event) { ... }, { scope: 'past' });
  });

  adobeDataLayer.push({
    event: 'change'
  });

  // ACDL gets initialized afterwards
```
Result: event listener will **not** be triggered

2. Event listener with scope set to future, late ACDL initialization:
```
  adobeDataLayer.push(function(adobeDataLayer) {
    adobeDataLayer.addEventListener('change', function(event) { ... }, { scope: 'future' });
  });

  adobeDataLayer.push({
    event: 'change'
  });

  // ACDL gets initialized afterwards
```
Result: event listener will be triggered

3. Event listener with scope set to past, early ACDL initialization:
```
  // ACDL gets initialized before

  adobeDataLayer.push(function(adobeDataLayer) {
    adobeDataLayer.addEventListener('change', function(event) { ... }, { scope: 'past' });
  });

  adobeDataLayer.push({
    event: 'change'
  });
```
Result: event listener will be triggered

4. Event listener with scope set to future, late ACDL initialization:
```
  // ACDL gets initialized before

  adobeDataLayer.push(function(adobeDataLayer) {
    adobeDataLayer.addEventListener('change', function(event) { ... }, { scope: 'future' });
  });

  adobeDataLayer.push({
    event: 'change'
  });
```
Result: event listener will **not** be triggered

### CODE REVIEW

File: src/dataLayerManager.js [hunk 1]
```diff
@@ -210,7 +218,11 @@ module.exports = function(config) {
         _dataLayer.splice(i, 1);
         i--;
       }
+
+      i++;
     }
+
+    _dataLayer.processed = true;
```
Comment (jckautzmann) [inline src/dataLayerManager.js:225]: I'd call the property `initialized` instead of `processed`. IMHO the data layer is `initialized` after all items have been `processed`.

**Comment by jckautzmann** [comment]
We should have a new test to verify the correct behaviour as described in https://github.com/adobe/adobe-client-data-layer/issues/100

**Review by jckautzmann — APPROVED** [review]
